---
- name: Install required packages
  become: true
  ansible.builtin.dnf:
    name:
      - zsh
      - git
      - curl
    state: present

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: oh_my_zsh_installed

- name: Download and install Oh My Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: not oh_my_zsh_installed.stat.exists

- name: Set Zsh as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh

- name: Create .zshrc backup
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc.backup"
    remote_src: yes
    force: no
  when: oh_my_zsh_installed.stat.exists

- name: Configure ZSH theme
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="robbyrussell"'

- name: Add zsh-autosuggestions repository
  become: true
  ansible.builtin.get_url:
    url: https://download.opensuse.org/repositories/shells:zsh-users:zsh-autosuggestions/Fedora_Rawhide/shells:zsh-users:zsh-autosuggestions.repo
    dest: /etc/yum.repos.d/shells:zsh-users:zsh-autosuggestions.repo
    mode: '0644'

- name: Install zsh-autosuggestions
  become: true
  ansible.builtin.dnf:
    name: zsh-autosuggestions
    state: present

- name: Clone zsh-autosuggestions git directory
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    state: present

- name: Install zsh-syntax-highlighting
  become: true
  ansible.builtin.dnf:
    name: zsh-syntax-highlighting
    state: present

- name: Clone zsh-syntax-highlighting git directory
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    state: present

- name: Clone you-should-use git directory
  ansible.builtin.git:
    repo: 'https://github.com/MichaelAquilina/zsh-you-should-use.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/you-should-use"
    state: present

- name: Clone zsh-bat git directory
  ansible.builtin.git:
    repo: 'https://github.com/fdellwing/zsh-bat.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-bat"
    state: present