---
- name: Add Flatpak repository
  become: true
  ansible.builtin.get_url:
    url: https://dl.flathub.org/repo/flathub.flatpakrepo
    dest: /etc/yum.repos.d/flathub.flatpakrepo
    mode: '0644'

- name: Install Flatpak
  become: true
  ansible.builtin.dnf:
    name: flatpak
    state: present

- name: Add Flathub remote
  become: true
  ansible.builtin.command:
    cmd: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo