---
galaxy_info:
  author: romainbellande
  description: Install just command runner
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
